from __future__ import annotations

import json
import shutil
from collections.abc import Callable
from pathlib import Path
from typing import Any

from repomind.core.config import get_settings
from repomind.llm.prompts import report_prompt, synthesis_prompt
from repomind.llm.registry import local_model

REPORT_NAMES = [
    "README.md",
    "ARCHITECTURE.md",
    "SECURITY_REPORT.md",
    "TECH_DEBT.md",
    "RECRUITER_REVIEW.md",
    "CTO_REVIEW.md",
    "ROADMAP.md",
    "PROJECT_STATUS.md",
]


def generate_reports(repo: dict[str, Any], summary: dict[str, Any]) -> dict[str, str]:
    settings = get_settings()
    out_dir = settings.reports_dir / "generated" / repo["id"]
    out_dir.mkdir(parents=True, exist_ok=True)
    ai = _synthesize_reports(summary)
    writers: dict[str, Callable[[dict[str, Any], dict[str, str]], str]] = {
        "README.md": _readme,
        "ARCHITECTURE.md": _architecture,
        "SECURITY_REPORT.md": _security,
        "TECH_DEBT.md": _debt,
        "RECRUITER_REVIEW.md": _recruiter,
        "CTO_REVIEW.md": _cto,
        "ROADMAP.md": _roadmap,
        "PROJECT_STATUS.md": _status,
    }
    paths: dict[str, str] = {}
    for name, writer in writers.items():
        path = out_dir / name
        path.write_text(writer(summary, ai))
        paths[name] = str(path)
    (out_dir / "analysis-summary.json").write_text(json.dumps(summary, indent=2))
    paths["analysis-summary.json"] = str(out_dir / "analysis-summary.json")
    return paths


def export_bundle(repo_id: str) -> Path:
    settings = get_settings()
    source = settings.reports_dir / "generated" / repo_id
    if not source.exists():
        raise FileNotFoundError(repo_id)
    target = settings.exports_dir / f"{repo_id}-reports"
    archive = shutil.make_archive(str(target), "zip", source)
    return Path(archive)


def _header(title: str, summary: dict[str, Any]) -> str:
    repo = summary["repository"]
    return f"# {title}\n\nRepository: `{repo['name']}`\n\nGenerated by RepoMind AI using local-only qwen-judge inference.\n\n"


def _readme(summary: dict[str, Any], ai: dict[str, str]) -> str:
    stats = summary["statistics"]
    return (
        _header("RepoMind AI Repository Brief", summary)
        + f"## Overview\n\n{summary['architecture']['summary']}\n\n"
        + f"## Key Stats\n\n- Files analyzed: {stats['files']}\n- Functions: {stats['functions']}\n- Methods: {stats['methods']}\n- Classes: {stats['classes']}\n- Routes: {stats['routes']}\n- Database models: {stats['database_models']}\n- Indexed chunks: {stats['indexed_chunks']}\n\n"
        + f"## Detected Stack\n\n- Primary language: {summary['languages']['primary']}\n- Frameworks: {', '.join(summary['stack']['frameworks']) or 'None detected'}\n- Package managers: {', '.join(summary['stack']['package_managers']) or 'None detected'}\n\n"
        + _ai_section("Local Model Brief", ai["overview"])
        + "## Generated Reports\n\n- ARCHITECTURE.md\n- SECURITY_REPORT.md\n- TECH_DEBT.md\n- RECRUITER_REVIEW.md\n- CTO_REVIEW.md\n- ROADMAP.md\n"
    )


def _architecture(summary: dict[str, Any], ai: dict[str, str]) -> str:
    arch = summary["architecture"]
    important = "\n".join(f"- `{path}`" for path in arch["important_files"]) or "- No graph centrality signals found."
    dirs = "\n".join(f"- `{path}`" for path in arch["top_level_directories"]) or "- Flat repository."
    diagrams = arch.get("diagrams", {})
    diagram_blocks = "\n\n".join(
        f"## {label}\n\n```mermaid\n{body}\n```"
        for label, body in [
            ("System Diagram", diagrams.get("system")),
            ("Component Diagram", diagrams.get("component")),
            ("Dependency Diagram", diagrams.get("dependency")),
            ("Service Diagram", diagrams.get("service")),
            ("Data Flow Diagram", diagrams.get("data_flow")),
        ]
        if body
    )
    return (
        _header("Architecture", summary)
        + f"## Inferred Style\n\n{arch['style']}\n\n## Summary\n\n{arch['summary']}\n\n"
        + f"## Top-Level Directories\n\n{dirs}\n\n## Important Files\n\n{important}\n\n"
        + _ai_section("Architecture Explanation", ai["architecture"])
        + diagram_blocks
        + "\n"
    )


def _security(summary: dict[str, Any], ai: dict[str, str]) -> str:
    findings = summary["security"]["findings"]
    rows = "\n".join(
        f"- **{item['severity']}** `{item['path']}:{item['line']}` `{item['rule_id']}` - {item['message']}"
        for item in findings[:100]
    ) or "- No high-confidence findings from enabled scanners."
    return (
        _header("Security Report", summary)
        + f"Security score: **{summary['scores']['security']} / 100**\n\n"
        + _score_details("security", summary)
        + f"Scanner status: `{summary['security']['scanner_status']}`\n\n"
        + f"Severity counts: `{summary['security']['severity_counts']}`\n\n## Findings\n\n{rows}\n\n"
        + _ai_section("Local Model Security Assessment", ai["technical"])
        + "## Next Steps\n\n- Review high severity findings first.\n- Add scanner execution to CI before public release.\n- Keep generated reports private when they include sensitive paths or secrets.\n"
    )


def _debt(summary: dict[str, Any], ai: dict[str, str]) -> str:
    debt = summary["technical_debt"]
    items = "\n".join(
        f"- `{item['path']}:{item['line']}` {item['message']} ({item['severity']})"
        for item in debt["items"][:100]
    ) or "- No major complexity findings detected."
    todos = "\n".join(f"- `{item['path']}` {item['tag']}: {item['text']}" for item in debt["todos"][:50]) or "- No TODO/FIXME markers detected."
    return (
        _header("Technical Debt", summary)
        + f"Maintainability score: **{debt['score']} / 100**\n\n"
        + _score_details("maintainability", summary)
        + f"## Complexity\n\n{items}\n\n## Markers\n\n{todos}\n\n"
        + _ai_section("Local Model Debt Assessment", ai["technical"])
    )


def _recruiter(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return (
        _header("Recruiter Review", summary)
        + f"Recruiter score: **{summary['scores']['recruiter']} / 100**\n\n"
        + _score_details("recruiter", summary)
        + "## Hiring Signal\n\n"
        + ai["recruiter"]
        + "\n\n## Evidence\n\n"
        + f"- Primary language: {summary['languages']['primary']}\n- Frameworks: {', '.join(summary['stack']['frameworks']) or 'None detected'}\n- Files analyzed: {summary['statistics']['files']}\n"
        + _evidence_files(summary)
    )


def _cto(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return (
        _header("CTO Review", summary)
        + f"CTO score: **{summary['scores']['cto']} / 100**\n\n"
        + _score_details("cto", summary)
        + "## Executive View\n\n"
        + ai["cto"]
        + "\n\n## Risk Snapshot\n\n"
        + f"- Security score: {summary['scores']['security']}\n- Maintainability score: {summary['scores']['maintainability']}\n- Production readiness: {summary['scores']['production_readiness']}\n"
        + _evidence_files(summary)
    )


def _roadmap(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return (
        _header("Roadmap", summary)
        + _ai_section("Local Model Roadmap", ai["technical"])
        + "## Recommended Next Steps\n\n"
        + "1. Resolve high severity security findings.\n"
        + "2. Add or strengthen automated tests around important files.\n"
        + "3. Reduce high-complexity functions and document major architecture decisions.\n"
        + "4. Add CI checks for linting, tests, dependency review, and secret scanning.\n"
        + "5. Re-run RepoMind AI after remediation to compare scores.\n"
    )


def _status(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return (
        _header("Project Status", summary)
        + f"## Scores\n\n```json\n{json.dumps(summary['scores'], indent=2)}\n```\n\n"
        + f"## Performance\n\n```json\n{json.dumps(summary.get('performance', {}), indent=2)}\n```\n\n"
        + f"## Model Status\n\n```json\n{json.dumps(local_model().status(), indent=2)}\n```\n"
        + _ai_section("Local Model Status Interpretation", ai["overview"])
    )


def _score_details(score_name: str, summary: dict[str, Any]) -> str:
    detail = summary.get("scores", {}).get("details", {}).get(score_name)
    if not detail:
        return ""
    positives = "\n".join(f"- {item}" for item in detail.get("positive_contributors", []))
    negatives = "\n".join(f"- {item}" for item in detail.get("negative_contributors", []))
    return (
        "## Score Evidence\n\n"
        f"Calculation: {detail.get('calculation')}\n\n"
        f"Positive contributors:\n\n{positives or '- None'}\n\n"
        f"Negative contributors:\n\n{negatives or '- None'}\n\n"
    )


def _ai_section(title: str, generated: str) -> str:
    return f"## {title}\n\n{generated}\n\n"


def _synthesize_reports(summary: dict[str, Any]) -> dict[str, str]:
    model = local_model()
    return {
        "overview": model.generate(synthesis_prompt("repository overview and project status", summary), 180),
        "architecture": model.generate(synthesis_prompt("architecture explanation with file-level evidence", summary), 220),
        "technical": model.generate(synthesis_prompt("security, technical debt, and roadmap", summary), 220),
        "recruiter": model.generate(report_prompt("recruiter review with evidence and confidence", summary), 220),
        "cto": model.generate(report_prompt("CTO review with evidence, risk, and confidence", summary), 220),
    }


def _evidence_files(summary: dict[str, Any]) -> str:
    files: list[str] = []
    files.extend(summary["architecture"].get("important_files", [])[:6])
    files.extend(summary["architecture"].get("route_files", [])[:6])
    files.extend(item.get("path") for item in summary["security"].get("findings", [])[:6] if item.get("path"))
    unique = [item for index, item in enumerate(files) if item and item not in files[:index]]
    if not unique:
        return ""
    return "\nEvidence files:\n" + "\n".join(f"- `{path}`" for path in unique[:12]) + "\n"
