from __future__ import annotations

import json
import shutil
from collections.abc import Callable as CollectionsCallable
from html import escape
from pathlib import Path
from typing import Any

from repomind.core.config import get_settings
from repomind.intelligence.architecture_explorer import render_onboarding_markdown
from repomind.intelligence.due_diligence import (
    build_cto_due_diligence,
    render_cto_due_diligence_markdown,
)
from repomind.intelligence.executive_reports import (
    build_executive_report_pack,
    render_report_pack_markdown,
)
from repomind.llm.prompts import report_prompt, synthesis_prompt
from repomind.llm.registry import local_model
from repomind.security.redaction import redact_text

REPORT_NAMES = [
    "README.md",
    "ARCHITECTURE.md",
    "SECURITY_REPORT.md",
    "TECH_DEBT.md",
    "RECRUITER_REVIEW.md",
    "CTO_REVIEW.md",
    "CTO_DUE_DILIGENCE.md",
    "EXECUTIVE_REPORT_PACK.md",
    "ONBOARDING.md",
    "ROADMAP.md",
    "PROJECT_STATUS.md",
]
EXTRA_REPORT_NAMES = ["SECURITY.sarif", "EXECUTIVE_SUMMARY.html", "EXECUTIVE_SUMMARY.pdf"]
CancelCheck = CollectionsCallable[[], bool]


def generate_reports(
    repo: dict[str, Any], summary: dict[str, Any], cancel_check: CancelCheck | None = None
) -> dict[str, str]:
    settings = get_settings()
    out_dir = settings.reports_dir / "generated" / repo["id"]
    out_dir.mkdir(parents=True, exist_ok=True)
    summary = _redacted_summary(summary)
    ai = _synthesize_reports(summary, cancel_check=cancel_check)
    writers: dict[str, CollectionsCallable[[dict[str, Any], dict[str, str]], str]] = {
        "README.md": _readme,
        "ARCHITECTURE.md": _architecture,
        "SECURITY_REPORT.md": _security,
        "TECH_DEBT.md": _debt,
        "RECRUITER_REVIEW.md": _recruiter,
        "CTO_REVIEW.md": _cto,
        "CTO_DUE_DILIGENCE.md": _due_diligence,
        "EXECUTIVE_REPORT_PACK.md": _executive_pack,
        "ONBOARDING.md": _onboarding,
        "ROADMAP.md": _roadmap,
        "PROJECT_STATUS.md": _status,
    }
    paths: dict[str, str] = {}
    for name in REPORT_NAMES:
        _checkpoint(cancel_check)
        writer = writers[name]
        path = out_dir / name
        path.write_text(redact_text(writer(summary, ai)))
        paths[name] = str(path)
    sarif_path = out_dir / "SECURITY.sarif"
    sarif_path.write_text(json.dumps(_sarif(summary), indent=2))
    paths[sarif_path.name] = str(sarif_path)
    html_path = out_dir / "EXECUTIVE_SUMMARY.html"
    html_path.write_text(_html_summary(summary))
    paths[html_path.name] = str(html_path)
    pdf_path = out_dir / "EXECUTIVE_SUMMARY.pdf"
    pdf_path.write_bytes(_pdf_summary(summary))
    paths[pdf_path.name] = str(pdf_path)
    (out_dir / "analysis-summary.json").write_text(redact_text(json.dumps(summary, indent=2)))
    paths["analysis-summary.json"] = str(out_dir / "analysis-summary.json")
    return paths


def export_bundle(repo_id: str) -> Path:
    settings = get_settings()
    source = settings.reports_dir / "generated" / repo_id
    if not source.exists():
        raise FileNotFoundError(repo_id)
    target = settings.exports_dir / f"{repo_id}-reports"
    archive = shutil.make_archive(str(target), "zip", source)
    return Path(archive)


def compare_summaries(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    left_scores = left.get("scores", {})
    right_scores = right.get("scores", {})
    left_stats = left.get("statistics", {})
    right_stats = right.get("statistics", {})
    return {
        "left": left.get("repository", {}),
        "right": right.get("repository", {}),
        "score_delta": {
            key: _number(right_scores.get(key)) - _number(left_scores.get(key))
            for key in sorted(set(left_scores) | set(right_scores))
            if key != "details"
        },
        "statistics_delta": {
            key: _number(right_stats.get(key)) - _number(left_stats.get(key))
            for key in sorted(set(left_stats) | set(right_stats))
        },
        "stack_added": sorted(
            set(right.get("stack", {}).get("frameworks", []))
            - set(left.get("stack", {}).get("frameworks", []))
        ),
        "stack_removed": sorted(
            set(left.get("stack", {}).get("frameworks", []))
            - set(right.get("stack", {}).get("frameworks", []))
        ),
    }


def _header(title: str, summary: dict[str, Any]) -> str:
    repo = summary["repository"]
    return f"# {title}\n\nRepository: `{repo['name']}`\n\nGenerated by RepoMind AI using local-only qwen-judge inference.\n\n"


def _readme(summary: dict[str, Any], ai: dict[str, str]) -> str:
    stats = summary["statistics"]
    return (
        _header("RepoMind AI Repository Brief", summary)
        + f"## Overview\n\n{summary['architecture']['summary']}\n\n"
        + f"## Key Stats\n\n- Files analyzed: {stats['files']}\n- Functions: {stats['functions']}\n- Methods: {stats['methods']}\n- Classes: {stats['classes']}\n- Routes: {stats['routes']}\n- Database models: {stats['database_models']}\n- Indexed chunks: {stats['indexed_chunks']}\n\n"
        + f"## Detected Stack\n\n- Primary language: {summary['languages']['primary']}\n- Frameworks: {', '.join(summary['stack']['frameworks']) or 'None detected'}\n- Package managers: {', '.join(summary['stack']['package_managers']) or 'None detected'}\n\n"
        + _ai_section("Local Model Brief", ai["overview"])
        + "## Generated Reports\n\n- ARCHITECTURE.md\n- SECURITY_REPORT.md\n- TECH_DEBT.md\n- RECRUITER_REVIEW.md\n- CTO_REVIEW.md\n- ROADMAP.md\n"
    )


def _architecture(summary: dict[str, Any], ai: dict[str, str]) -> str:
    arch = summary["architecture"]
    important = (
        "\n".join(f"- `{path}`" for path in arch["important_files"])
        or "- No graph centrality signals found."
    )
    dirs = (
        "\n".join(f"- `{path}`" for path in arch["top_level_directories"]) or "- Flat repository."
    )
    diagrams = arch.get("diagrams", {})
    diagram_blocks = "\n\n".join(
        f"## {label}\n\n```mermaid\n{body}\n```"
        for label, body in [
            ("System Diagram", diagrams.get("system")),
            ("Component Diagram", diagrams.get("component")),
            ("Dependency Diagram", diagrams.get("dependency")),
            ("Service Diagram", diagrams.get("service")),
            ("Data Flow Diagram", diagrams.get("data_flow")),
        ]
        if body
    )
    return (
        _header("Architecture", summary)
        + f"## Inferred Style\n\n{arch['style']}\n\n## Summary\n\n{arch['summary']}\n\n"
        + f"## Top-Level Directories\n\n{dirs}\n\n## Important Files\n\n{important}\n\n"
        + _ai_section("Architecture Explanation", ai["architecture"])
        + diagram_blocks
        + "\n"
    )


def _security(summary: dict[str, Any], ai: dict[str, str]) -> str:
    findings = summary["security"]["findings"]
    rows = (
        "\n".join(
            f"- **{item['severity']}** `{item['path']}:{item['line']}` `{item['rule_id']}` - {item['message']}"
            for item in findings[:100]
        )
        or "- No high-confidence findings from enabled scanners."
    )
    return (
        _header("Security Report", summary)
        + f"Security score: **{summary['scores']['security']} / 100**\n\n"
        + _score_details("security", summary)
        + f"Scanner status: `{summary['security']['scanner_status']}`\n\n"
        + f"Severity counts: `{summary['security']['severity_counts']}`\n\n## Findings\n\n{rows}\n\n"
        + _ai_section("Local Model Security Assessment", ai["technical"])
        + "## Next Steps\n\n- Review high severity findings first.\n- Add scanner execution to CI before public release.\n- Keep generated reports private when they include sensitive paths or secrets.\n"
    )


def _debt(summary: dict[str, Any], ai: dict[str, str]) -> str:
    debt = summary["technical_debt"]
    items = (
        "\n".join(
            f"- `{item['path']}:{item['line']}` {item['message']} ({item['severity']})"
            for item in debt["items"][:100]
        )
        or "- No major complexity findings detected."
    )
    todos = (
        "\n".join(
            f"- `{item['path']}` {item['tag']}: {item['text']}" for item in debt["todos"][:50]
        )
        or "- No TODO/FIXME markers detected."
    )
    return (
        _header("Technical Debt", summary)
        + f"Maintainability score: **{debt['score']} / 100**\n\n"
        + _score_details("maintainability", summary)
        + f"## Complexity\n\n{items}\n\n## Markers\n\n{todos}\n\n"
        + _ai_section("Local Model Debt Assessment", ai["technical"])
    )


def _recruiter(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return (
        _header("Recruiter Review", summary)
        + f"Recruiter score: **{summary['scores']['recruiter']} / 100**\n\n"
        + _score_details("recruiter", summary)
        + "## Hiring Signal\n\n"
        + ai["recruiter"]
        + "\n\n## Evidence\n\n"
        + f"- Primary language: {summary['languages']['primary']}\n- Frameworks: {', '.join(summary['stack']['frameworks']) or 'None detected'}\n- Files analyzed: {summary['statistics']['files']}\n"
        + _evidence_files(summary)
    )


def _cto(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return (
        _header("CTO Review", summary)
        + f"CTO score: **{summary['scores']['cto']} / 100**\n\n"
        + _score_details("cto", summary)
        + "## Executive View\n\n"
        + ai["cto"]
        + "\n\n## Risk Snapshot\n\n"
        + f"- Security score: {summary['scores']['security']}\n- Maintainability score: {summary['scores']['maintainability']}\n- Production readiness: {summary['scores']['production_readiness']}\n"
        + _evidence_files(summary)
    )


def _due_diligence(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return render_cto_due_diligence_markdown(build_cto_due_diligence(summary))


def _executive_pack(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return render_report_pack_markdown(build_executive_report_pack(summary))


def _onboarding(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return render_onboarding_markdown(summary)


def _roadmap(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return (
        _header("Roadmap", summary)
        + _ai_section("Local Model Roadmap", ai["technical"])
        + "## Recommended Next Steps\n\n"
        + "1. Resolve high severity security findings.\n"
        + "2. Add or strengthen automated tests around important files.\n"
        + "3. Reduce high-complexity functions and document major architecture decisions.\n"
        + "4. Add CI checks for linting, tests, dependency review, and secret scanning.\n"
        + "5. Re-run RepoMind AI after remediation to compare scores.\n"
    )


def _status(summary: dict[str, Any], ai: dict[str, str]) -> str:
    return (
        _header("Project Status", summary)
        + f"## Scores\n\n```json\n{json.dumps(summary['scores'], indent=2)}\n```\n\n"
        + f"## Performance\n\n```json\n{json.dumps(summary.get('performance', {}), indent=2)}\n```\n\n"
        + f"## Model Status\n\n```json\n{json.dumps(local_model().status(), indent=2)}\n```\n"
        + _ai_section("Local Model Status Interpretation", ai["overview"])
    )


def _sarif(summary: dict[str, Any]) -> dict[str, Any]:
    findings = summary.get("security", {}).get("findings", [])
    return {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "RepoMind AI",
                        "informationUri": "https://github.com",
                        "rules": _sarif_rules(findings),
                    }
                },
                "results": [_sarif_result(item) for item in findings],
            }
        ],
    }


def _sarif_rules(findings: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rules = {}
    for item in findings:
        rule_id = item.get("rule_id", "repomind")
        rules[rule_id] = {
            "id": rule_id,
            "name": rule_id,
            "shortDescription": {"text": item.get("message", "RepoMind AI security finding")},
            "properties": {
                "security-severity": _sarif_security_severity(item.get("severity", "medium"))
            },
        }
    return list(rules.values())


def _sarif_result(item: dict[str, Any]) -> dict[str, Any]:
    return {
        "ruleId": item.get("rule_id", "repomind"),
        "level": _sarif_level(item.get("severity", "medium")),
        "message": {"text": item.get("message", "RepoMind AI security finding")},
        "locations": [
            {
                "physicalLocation": {
                    "artifactLocation": {"uri": item.get("path", "")},
                    "region": {"startLine": item.get("line", 1)},
                }
            }
        ],
    }


def _html_summary(summary: dict[str, Any]) -> str:
    scores = summary.get("scores", {})
    stats = summary.get("statistics", {})
    rows = "".join(
        f"<tr><th>{escape(str(key))}</th><td>{escape(str(value))}</td></tr>"
        for key, value in {
            "Repository": summary.get("repository", {}).get("name"),
            "Files": stats.get("files"),
            "Primary language": summary.get("languages", {}).get("primary"),
            "Security": scores.get("security"),
            "Maintainability": scores.get("maintainability"),
            "Production readiness": scores.get("production_readiness"),
        }.items()
    )
    return (
        "<!doctype html><html><head><meta charset='utf-8'><title>RepoMind Executive Summary</title>"
        "<style>body{font-family:Inter,Arial,sans-serif;margin:40px;color:#111827}"
        "table{border-collapse:collapse}th,td{border:1px solid #d1d5db;padding:8px 12px;text-align:left}</style>"
        "</head><body><h1>RepoMind Executive Summary</h1>"
        f"<p>{escape(summary.get('architecture', {}).get('summary', 'No architecture summary available.'))}</p>"
        f"<table>{rows}</table></body></html>"
    )


def _pdf_summary(summary: dict[str, Any]) -> bytes:
    lines = [
        "RepoMind Executive Summary",
        f"Repository: {summary.get('repository', {}).get('name')}",
        f"Files: {summary.get('statistics', {}).get('files')}",
        f"Security: {summary.get('scores', {}).get('security')}",
        f"Maintainability: {summary.get('scores', {}).get('maintainability')}",
        f"Production readiness: {summary.get('scores', {}).get('production_readiness')}",
    ]
    stream = (
        "BT /F1 12 Tf 72 760 Td "
        + " Tj 0 -18 Td ".join(f"({_pdf_escape(line)})" for line in lines)
        + " Tj ET"
    )
    objects = [
        "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
        "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
        "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
        "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
        f"5 0 obj << /Length {len(stream.encode())} >> stream\n{stream}\nendstream endobj",
    ]
    body = "%PDF-1.4\n" + "\n".join(objects) + "\ntrailer << /Root 1 0 R >>\n%%EOF\n"
    return body.encode()


def _pdf_escape(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _sarif_level(severity: str) -> str:
    return {"critical": "error", "high": "error", "medium": "warning", "low": "note"}.get(
        str(severity).lower(), "warning"
    )


def _sarif_security_severity(severity: str) -> str:
    return {"critical": "9.5", "high": "8.0", "medium": "5.0", "low": "2.0"}.get(
        str(severity).lower(), "5.0"
    )


def _number(value: Any) -> float:
    return float(value) if isinstance(value, (int, float)) else 0.0


def _score_details(score_name: str, summary: dict[str, Any]) -> str:
    detail = summary.get("scores", {}).get("details", {}).get(score_name)
    if not detail:
        return ""
    positives = "\n".join(f"- {item}" for item in detail.get("positive_contributors", []))
    negatives = "\n".join(f"- {item}" for item in detail.get("negative_contributors", []))
    return (
        "## Score Evidence\n\n"
        f"Calculation: {detail.get('calculation')}\n\n"
        f"Positive contributors:\n\n{positives or '- None'}\n\n"
        f"Negative contributors:\n\n{negatives or '- None'}\n\n"
    )


def _ai_section(title: str, generated: str) -> str:
    return f"## {title}\n\n{generated}\n\n"


def _synthesize_reports(
    summary: dict[str, Any], cancel_check: CancelCheck | None = None
) -> dict[str, str]:
    model = local_model()
    return {
        "overview": _safe_generate(
            model,
            synthesis_prompt("repository overview and project status", summary),
            180,
            summary,
            cancel_check,
        ),
        "architecture": _safe_generate(
            model,
            synthesis_prompt("architecture explanation with file-level evidence", summary),
            220,
            summary,
            cancel_check,
        ),
        "technical": _safe_generate(
            model,
            synthesis_prompt("security, technical debt, and roadmap", summary),
            220,
            summary,
            cancel_check,
        ),
        "recruiter": _safe_generate(
            model,
            report_prompt("recruiter review with evidence and confidence", summary),
            220,
            summary,
            cancel_check,
        ),
        "cto": _safe_generate(
            model,
            report_prompt("CTO review with evidence, risk, and confidence", summary),
            220,
            summary,
            cancel_check,
        ),
    }


def _safe_generate(
    model: Any,
    prompt: str,
    max_tokens: int,
    summary: dict[str, Any],
    cancel_check: CancelCheck | None = None,
) -> str:
    _checkpoint(cancel_check)
    try:
        generated = model.generate(prompt, max_tokens)
        _checkpoint(cancel_check)
        return generated
    except RuntimeError as exc:
        return _evidence_only_model_fallback(summary, exc)


def _evidence_only_model_fallback(summary: dict[str, Any], exc: RuntimeError) -> str:
    return (
        "Local model generation was unavailable, so this section uses deterministic repository evidence only.\n\n"
        f"- Model status: {exc}\n"
        f"- Architecture style: {summary['architecture'].get('style')}\n"
        f"- Files analyzed: {summary['statistics'].get('files')}\n"
        f"- Primary language: {summary['languages'].get('primary')}\n"
        f"- Security score: {summary['scores'].get('security')}\n"
        f"- Maintainability score: {summary['scores'].get('maintainability')}\n"
    )


def _redacted_summary(summary: dict[str, Any]) -> dict[str, Any]:
    payload = json.loads(json.dumps(summary))
    for finding in payload.get("security", {}).get("findings", []):
        if "message" in finding:
            finding["message"] = redact_text(str(finding["message"]))
    for todo in payload.get("technical_debt", {}).get("todos", []):
        if "text" in todo:
            todo["text"] = redact_text(str(todo["text"]))
    return payload


def _evidence_files(summary: dict[str, Any]) -> str:
    files: list[str] = []
    files.extend(summary["architecture"].get("important_files", [])[:6])
    files.extend(summary["architecture"].get("route_files", [])[:6])
    files.extend(
        item.get("path") for item in summary["security"].get("findings", [])[:6] if item.get("path")
    )
    unique = [item for index, item in enumerate(files) if item and item not in files[:index]]
    if not unique:
        return ""
    return "\nEvidence files:\n" + "\n".join(f"- `{path}`" for path in unique[:12]) + "\n"


def _checkpoint(cancel_check: CancelCheck | None) -> None:
    if cancel_check and cancel_check():
        from repomind.analysis.analyzer import AnalysisCancelled

        raise AnalysisCancelled("Analysis cancelled.")
